### ISSUE TITLE
not working with iTunes services

### ISSUE THREAD

**Issue by albza** [Garulf/window-services#9]
I normally keep iTunes services set to manual and I only start them when I need to sync my phone. 
Today I found out that the Bonjour Service cannot be started by this plugin. Unfortunately I have no clue why.

Anyway, thank you for this plugin which I appreciate a lot.

**Comment by Garulf** [comment]
Behind the scenes this plugin is just using Window's own command utility for controlling services. 

Some services do require admin privileges however. Are you using an account that is not admin?

**Comment by Garulf** [comment]
This was fixed in latest release.
